# -*- coding: utf-8 -*-
"""getSuitable&img_link-Done.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/131O6hoNNM94yB4n9YsMoBAdR86tZvPza
"""

#最終結果: 油性有84項產品,乾性有245項產品
pName = []
oil = [] #儲存油性產品
dry = [] #儲存事性產品

#for write csv
Type = []
Product = []
Brand = []
Price = []

import csv

with open('productsName.csv',newline='',encoding="Big5") as csvfile:
    for line in csvfile.readlines():
        data = line.split(',')
        Type.append(data[0].strip())
        Product.append(data[1].strip())
        Brand.append(data[2].strip())
        pName.append(data[3].strip())
        Price.append(data[4].strip())

Type.remove('Type')
Product.remove('Product')
Brand.remove('Brand')
pName.remove('Name')
Price.remove('Price')

#不泛油光: 239
#不緊繃: 289

import requests
from bs4 import BeautifulSoup

header = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36'}
part1 = 'https://www.urcosme.com/tags/'
tags = ['239','289']
part2 = '/products?page='

def Get_Name(pList,tag):
    for i in range(1,31):
        url = part1 + tag + part2 + str(i)
        try:
            r = requests.get(url,headers=header)
            objSoup = BeautifulSoup(r.text,'lxml')
            name = objSoup.find_all('div','product-name single-dot')
            for j in range(len(name)):
                #產品名字
                pList.append(name[j].text.strip())
        except:
            print('failed')

Get_Name(oil,tags[0])
Get_Name(dry,tags[1])

suitable = [] #儲存適合油性還是乾性
for i in range(len(pName)):
    s = ''
    length = len(suitable)
    try:
        if oil.index(pName[i]) != -1:
            s = s + '油性'
    except:
        pass
    try:
        if dry.index(pName[i]) != -1:
            if s == '':
                s = s + '乾性'
            else:
                s = s + ',乾性'
    except:
        pass
    
    if s == '':
        suitable.append('None')
    else:
        suitable.append(s)

picLink = []
link = 'https://www.urcosme.com/search/product?keyword='
for i in range(len(pName)):
    length = len(picLink)
    if pName[i].find(' ') != -1:
        temp = pName[i].replace(' ','+')
    else:
        temp = pName[i]
    url = link + temp
    print(url)
    r = requests.get(url,headers=header)
    objSoup = BeautifulSoup(r.text,'lxml')
    pic = objSoup.find_all('div','product-image')
    for j in pic:
        picname = j.find("img")['alt']
        if picname == pName[i]:
            picLink.append(j.find("img")['src'])
            break
    if len(picLink) == length:
        picLink.append('https://dg9ugnb21lig7.cloudfront.net/uploads/images/product_default_160x160.png')

with open('product_withUse.csv','w',newline='',encoding="Big5") as csvfile:
    fieldnames = ['Type','Product','Brand','Name','Price','Suitable','img_link']
    writer = csv.DictWriter(csvfile, fieldnames = fieldnames)
    writer.writeheader()
    for i in range(len(pName)):
        try:
            writer.writerow({'Type':Type[i],'Product': Product[i], 'Brand': Brand[i], 'Name':pName[i], 'Price':Price[i],'Suitable':suitable[i],'img_link':picLink[i]})
        except IndexError as e:
            print(e)