# -*- coding: utf-8 -*-
"""GettingProductsIngredient.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pbrv0yGHBL8LcCo7naWhymKKBUZrANgO
"""

#讀出產品名稱以方便爬取成分網址
import csv
import re

name = []
with open('productsName.csv',newline='',encoding="Big5") as csvfile:
    for line in csvfile.readlines():
        data = line.split(',')
        temp = data[3].strip('\r\n')
        temp = temp.split()
        t = ''
        for i in temp:
            pTemp = re.sub('[a-zA-Z0-9+/\-*★.．卅&\'#“”–()Ⅱ%﹢:\[\];（）!’×「」°]','',i)
            if pTemp != '':
                name.append(pTemp)
print('Done with saving data.')

#於CosDNA找出產品並爬取成分網址
import time
import requests
from bs4 import BeautifulSoup

url = 'https://www.cosdna.com/cht/product.php?q='
sort = '&sort=date'
header = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36'}
cnt = 0
allLink = []
for i in name:
    if len(allLink) == 30: break
    time.sleep(1)
    link = url + i + sort
    try:
        r = requests.get(link,headers=header)
        objSoup = BeautifulSoup(r.text,'lxml')
        fLink = objSoup.find('td','pl-0').find('a')
        temp = 'https://www.cosdna.com' + fLink.get('href')
        allLink.append(temp)
    except:
        cnt = cnt + 1
        print('[',cnt,'] Cannot find this product: [',i,'] in CosDNA.')

#發現可於CosDNA找到的產品只有在5078項當中只有2594項可被找到, 理由分為: 
#(1) cosDNA沒有該項產品
#(2) cosDNA與urCosme上標注的名稱不一樣
#->解決方案:(1)另尋有該產品成分的網站*先把2594項做好再找* (2)針對這2484項沒被找到的產品名稱作調整

#於Skin Salvation找出成分致粉刺程度
#ssIngre = 成分名稱; snIngre = 成分致粉刺程度
url = 'https://skinsalvationsf.com/comedogenic/'
r = requests.get(url,headers=header)
header = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36'}
objSoup = BeautifulSoup(r.text,'lxml')
page = objSoup.find_all('tr')
ssIngre = []
snIngre = []
for i in range(len(page)):
    if(page[i].text.find('							 ') != -1):
        d = page[i].text.strip()
        d = d.replace('							 ',',')
        temp = d.split(',')
        for j in range(len(temp)):
            if j > 1:
                break
            elif j == 1:
                try:
                    snIngre.append(int(temp[j]))
                except:
                    snIngre.append(0)
            else:
                ssIngre.append(temp[j])

#找出產品成分
#pName = 成分名稱; pIngre = 所有產品對應成分;
#IngreChara = 所有成分特性; IngreAcne = 所有成分致粉刺; IngreSti = 所有成分刺激性; IngreSafe = 所有成分安全性
#IngreDalton = PubChem的分子量
import pubchempy as pcp

pIngre = []
pName = []
IngreChara = []
IngreAcne = []
IngreSti = []
IngreSafe = []
IngreDalton = []
for i in range(len(allLink)):
    if i == 30: break #試驗用只爬30個網址,若需全部資料即把這行刪掉
    r = requests.get(allLink[i],headers=header)
    objSoup = BeautifulSoup(r.text,'lxml')
    p = objSoup.find('span',{'class':'prod-name'})
    n = objSoup.find_all('span',{'class':'colors'})
    chara = objSoup.find_all('td','small-85 text-vampire align-middle')
    acne_sti_safe = objSoup.find_all('td','text-nowrap text-center align-middle')
    
    #拆成分
    iTemp = []
    for j in n:
        iTemp.append(j.text.strip())
        
    #拆特性
    cTemp = []
    for j in chara:
        if j.text.strip() == "":
            cTemp.append("None")
        elif len(j.text.strip().split(",")) >= 2:
            temp = j.text.strip().split(",")
            s = ''
            for k in range(len(temp)):
                if k == len(temp)-1:
                    s = s + temp[k].strip()
                else:
                    s = s + temp[k].strip() + ","
            cTemp.append(s)
        else:
            cTemp.append(j.text.strip())
            
    #拆粉刺&刺激&安心度
    aTemp = []
    stiTemp = []
    sTemp = []
    cnt = 0
    for j in range(len(acne_sti_safe)):
        data = acne_sti_safe[j].text.strip()
        if cnt == 0:
            if data == "":
                #若cosDNA沒有即到Skin Salvation找出
                query = iTemp[int(j/3)]
                tempLen = len(aTemp)
                for k in range(len(ssIngre)):
                    if ssIngre[k] == query:
                        aTemp.append(snIngre[k])
                        break
                if len(aTemp) == tempLen:
                    aTemp.append('0')
            else:
                aTemp.append(data)
            cnt = cnt + 1
        elif cnt == 1:
            if data == "":
                stiTemp.append('0')
            else:
                stiTemp.append(data)
            cnt = cnt + 1
        elif cnt == 2:
            if data == "":
                sTemp.append('None')
            else:
                sTemp.append(data)
            cnt = 0
    
    #找出成分阻塞
    dTemp = []
    for j in iTemp:
        if j.find('/') != -1:
            j = j[:j.find('/')]
        results = pcp.get_compounds(j, 'name')
        try:
            dTemp.append(results[0].molecular_weight)
        except:
            dTemp.append('None')

    pName.append(p.text.strip())
    pIngre.append(iTemp)
    IngreChara.append(cTemp)
    IngreDalton.append(dTemp)
    IngreSafe.append(sTemp)
    IngreAcne.append(aTemp)
    IngreSti.append(stiTemp)

#存成csv檔
#存資料庫時這些程式碼可刪掉(不用弄成csv再存)
with open('GoodProducts.csv','w',encoding='utf_8',newline='') as csvfile:
    fieldnames = ['Name','Ingredients','Character','Acne','Dalton','Stimulation','Safeness']
    writer = csv.DictWriter(csvfile, fieldnames = fieldnames)
    writer.writeheader()
    for i in range(0,10):
        temp = ''
        for j in pIngre[i]:
            temp = temp + j + ','
        writer.writerow({'Name':pName[i],'Ingredients':temp,'Character':IngreChara[i],'Acne':IngreAcne[i],'Dalton':IngreDalton[i],'Stimulation':IngreSti[i],'Safeness':IngreSafe[i]})
    
with open('BadProducts.csv','w',encoding='utf_8',newline='') as csvfile:
    fieldnames = ['Name','Ingredients','Character','Acne','Dalton','Stimulation','Safeness']
    writer = csv.DictWriter(csvfile, fieldnames = fieldnames)
    writer.writeheader()
    for i in range(10,20):
        temp = ''
        for j in pIngre[i]:
            temp = temp + j + ','
        writer.writerow({'Name':pName[i],'Ingredients':temp,'Character':IngreChara[i],'Acne':IngreAcne[i],'Dalton':IngreDalton[i],'Stimulation':IngreSti[i],'Safeness':IngreSafe[i]})

with open('QueryProducts.csv','w',encoding='utf_8',newline='') as csvfile:
    fieldnames = ['Name','Ingredients','Character','Acne','Dalton','Stimulation','Safeness']
    writer = csv.DictWriter(csvfile, fieldnames = fieldnames)
    writer.writeheader()
    for i in range(20,30):
        temp = ''
        for j in pIngre[i]:
            temp = temp + j + ','
        writer.writerow({'Name':pName[i],'Ingredients':temp,'Character':IngreChara[i],'Acne':IngreAcne[i],'Dalton':IngreDalton[i],'Stimulation':IngreSti[i],'Safeness':IngreSafe[i]})

"""# New Section"""